#!/usr/bin/env python

#######################################################################

CDB_OK = 0
CDB_ERROR = 1
CDB_CONFIGURATION_ERROR = 2
CDB_AUTHORIZATION_ERROR = 3
CDB_AUTHENTICATION_ERROR = 4
CDB_DB_ERROR = 5
CDB_INTERNAL_ERROR = 6
CDB_INVALID_ARGUMENT_ERROR = 7
CDB_INVALID_REQUEST_ERROR = 8
CDB_COMMAND_FAILED_ERROR = 9
CDB_COMMUNICATION_ERROR = 10 
CDB_URL_ERROR = 11 
CDB_OBJECT_NOT_FOUND = 12
CDB_OBJECT_ALREADY_EXISTS = 13


